#################################################
# Playbooks: Docker Install
#################################################
---
- hosts: managers,workers
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        pkg: "{{ item }}"
        state: present
        update_cache: true
        autoclean: true
        cache_valid_time: 3600
      become: true
      with_items:
        - aptitude
        - git
        - apt-transport-https
        - ca-certificates
        - curl

    - name: Set timezone to Europe/Belgrade
      community.general.timezone:
        name: Europe/Belgrade

    - name: Remove old docker packages
      ansible.builtin.apt:
        pkg: "{{ item }}"
        state: absent
        update_cache: true
        cache_valid_time: 3600
      become: true
      with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Ensures /etc/docker dir exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: 0755

    - name: Copy Docker deamon json config file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/daemon.json"
        dest: "/etc/docker/daemon.json"
        mode: 0644

    - name: Install docker-ce packages
      ansible.builtin.apt:
        pkg: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      become: true
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

      # sudo usermod -aG docker root
    - name: Add remote ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        append: true
        groups: docker
